# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/j2lte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/j2lte/proprietary/lib/libion_exynos.so:system/lib/libion_exynos.so \
    vendor/samsung/j2lte/proprietary/lib/libexynosutils.so:system/lib/libexynosutils.so \
    vendor/samsung/j2lte/proprietary/lib/libexynosv4l2.so:system/lib/libexynosv4l2.so \
    vendor/samsung/j2lte/proprietary/vendor/firmware/bcm43438A1_V0036.0112.hcd:system/vendor/firmware/bcm43438A1_V0036.0112.hcd \
    vendor/samsung/j2lte/proprietary/lib/hw/camera.exynos3.so:system/lib/hw/camera.exynos3.so \
    vendor/samsung/j2lte/proprietary/lib/libhwjpeg.so:system/lib/libhwjpeg.so \
    vendor/samsung/j2lte/proprietary/lib/libexynoscameraexternal.so:system/lib/libexynoscameraexternal.so \
    vendor/samsung/j2lte/proprietary/etc/srm.bin:system/etc/srm.bin \
    vendor/samsung/j2lte/proprietary/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    vendor/samsung/j2lte/proprietary/lib/libhdcp2.so:system/lib/libhdcp2.so \
    vendor/samsung/j2lte/proprietary/lib/libstagefright_hdcp.so:system/lib/libstagefright_hdcp.so \
    vendor/samsung/j2lte/proprietary/lib/libwvm.so:system/lib/libwvm.so \
    vendor/samsung/j2lte/proprietary/bin/gps.cer:system/bin/gps.cer \
    vendor/samsung/j2lte/proprietary/bin/gpsd:system/bin/gpsd \
    vendor/samsung/j2lte/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/j2lte/proprietary/etc/gps.xml:system/etc/gps.xml \
    vendor/samsung/j2lte/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/j2lte/proprietary/lib/libwrappergps.so:system/lib/libwrappergps.so \
    vendor/samsung/j2lte/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/samsung/j2lte/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    vendor/samsung/j2lte/proprietary/lib/hw/hwcomposer.exynos3.so:system/lib/hw/hwcomposer.exynos3.so \
    vendor/samsung/j2lte/proprietary/lib/hw/gralloc.exynos3.so:system/lib/hw/gralloc.exynos3.so \
    vendor/samsung/j2lte/proprietary/lib/libdisplay.so:system/lib/libdisplay.so \
    vendor/samsung/j2lte/proprietary/lib/libdisplaymodule.so:system/lib/libdisplaymodule.so \
    vendor/samsung/j2lte/proprietary/lib/libExynosHWCService.so:system/lib/libExynosHWCService.so \
    vendor/samsung/j2lte/proprietary/lib/libhdmimodule.so:system/lib/libhdmimodule.so \
    vendor/samsung/j2lte/proprietary/lib/libhdmi.so:system/lib/libhdmi.so \
    vendor/samsung/j2lte/proprietary/lib/libhwcutils.so:system/lib/libhwcutils.so \
    vendor/samsung/j2lte/proprietary/lib/libmpp.so:system/lib/libmpp.so \
    vendor/samsung/j2lte/proprietary/lib/libhwcutilsmodule.so:system/lib/libhwcutilsmodule.so \
    vendor/samsung/j2lte/proprietary/lib/hw/keystore.exynos3475.so:system/lib/hw/keystore.exynos3475.so \
    vendor/samsung/j2lte/proprietary/vendor/firmware/es305_fw.bin:system/vendor/firmware/es305_fw.bin \
    vendor/samsung/j2lte/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/samsung/j2lte/proprietary/vendor/firmware/es305_fw_bypass.bin:system/vendor/firmware/es305_fw_bypass.bin \
    vendor/samsung/j2lte/proprietary/lib/libgdmcprov.so:system/lib/libgdmcprov.so \
    vendor/samsung/j2lte/proprietary/lib/libMcClient.so:system/lib/libMcClient.so \
    vendor/samsung/j2lte/proprietary/lib/libMcRegistry.so:system/lib/libMcRegistry.so \
    vendor/samsung/j2lte/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/samsung/j2lte/proprietary/etc/plmn_delta.bin:system/etc/plmn_delta.bin \
    vendor/samsung/j2lte/proprietary/etc/plmn_se13.bin:system/etc/plmn_se13.bin \
    vendor/samsung/j2lte/proprietary/lib/libatparser.so:system/lib/libatparser.so \
    vendor/samsung/j2lte/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/j2lte/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/j2lte/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/j2lte/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/j2lte/proprietary/lib/hw/sensors.universal3475.so:system/lib/hw/sensors.universal3475.so \
    vendor/samsung/j2lte/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/j2lte/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/j2lte/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/j2lte/proprietary/lib/hw/audio.primary.universal3475.so:system/lib/hw/audio.primary.universal3475.so \
    vendor/samsung/j2lte/proprietary/lib/libaudio-ril.so:system/lib/libaudio-ril.so
